export const profiles = [
  "Rib-Type / Ribbed",
  "Corrugated",
  "Tile Profile",
  "Standing Seam",
  "R-Span",
  "Metal Deck",
  "Curved Roof",
  "Spandrel",
  "Other",
  "Not Determined",
];
export const accessories = [
  "Ridge Cap",
  "Valley Flashing",
  "Eaves Flashing",
  "Barge/Side Flashing",
  "Sidewall Flashing",
  "Endwall Flashing",
  "Drip Edge",
  "Gutter",
  "Downspout",
  "Closure Strip",
  "Ridge Roll",
  "Roofing Screws",
  "Sealant",
  "Other",
];
export function seed() {
  const materials = [
    ["Banawe", "SQM", 500],
    ["Twin Rib", "SQM", 550],
    ["Tilespan", "SQM", 600],
    ["R-Span", "SQM", 750],
    ["Standing Seam", "SQM", 800],
    ["Steel Decking", "SQM", 850],
    ["Ridge Cap", "LM", 250],
    ["Flashing", "LM", 300],
    ["Valley Flashing", "LM", 350],
    ["Eaves Flashing", "LM", 250],
    ["Barge/Side Flashing", "LM", 300],
    ["Roofing Screws", "PCS", 5],
    ["Sealant", "TUBE", 220],
    ["Closure Strips", "LM", 80],
    ["Gutter", "LM", 500],
    ["Downspout", "LM", 400],
  ].map(([name, unit, price], i) => ({
    id: `MAT-${i + 1}`,
    name,
    unit,
    price,
    category: i < 6 ? "Roofing Sheet" : "Accessory",
    thickness: i < 6 ? "0.40 mm" : "—",
    profile:
      i < 6
        ? [
            "Rib-Type / Ribbed",
            "Rib-Type / Ribbed",
            "Tile Profile",
            "R-Span",
            "Standing Seam",
            "Metal Deck",
          ][i]
        : "Other",
    active: true,
    history: [],
  }));
  const users = [
    {
      id: "USR-1",
      name: "Alex Morgan",
      role: "Admin",
      email: "alex@engroofing.example",
      contact: "0917 555 0100",
      initials: "AM",
      rate: 0,
    },
    {
      id: "USR-2",
      name: "Juan Dela Cruz",
      role: "Foreman",
      email: "juan@engroofing.example",
      contact: "0917 555 0101",
      initials: "JD",
      rate: 950,
    },
    {
      id: "USR-3",
      name: "Pedro Santos",
      role: "Employee",
      email: "pedro@engroofing.example",
      contact: "0917 555 0102",
      initials: "PS",
      rate: 750,
    },
    {
      id: "USR-4",
      name: "Mark Reyes",
      role: "Employee",
      email: "mark@engroofing.example",
      contact: "0917 555 0103",
      initials: "MR",
      rate: 750,
    },
    {
      id: "USR-5",
      name: "John Garcia",
      role: "Employee",
      email: "john@engroofing.example",
      contact: "0917 555 0104",
      initials: "JG",
      rate: 800,
    },
    {
      id: "USR-6",
      name: "Maria Santos",
      role: "Client",
      email: "maria@example.com",
      contact: "0917 555 0110",
      initials: "MS",
      rate: 0,
    },
  ];
  const specs = [
    [
      "Santos Residence",
      "Maria Santos",
      "Roof Replacement",
      "Residential",
      "Quezon City, Metro Manila",
      "Ongoing",
      65,
      132500,
      "2026-10-15",
    ],
    [
      "Greenfield Warehouse",
      "Robert Lim",
      "Roof Installation",
      "Industrial",
      "Pasig City, Metro Manila",
      "Ongoing",
      40,
      287000,
      "2026-10-22",
    ],
    [
      "Reyes Commercial Building",
      "Carla Reyes",
      "Roof Repair",
      "Commercial",
      "Makati City, Metro Manila",
      "Scheduled",
      0,
      78000,
      "2026-10-18",
    ],
    [
      "St. Matthew Learning Center",
      "Angela Cruz",
      "Roof Replacement",
      "Institutional",
      "Marikina City, Metro Manila",
      "Ongoing",
      85,
      196500,
      "2026-10-10",
    ],
    [
      "Dela Peña Residence",
      "Luis Dela Peña",
      "Roof Installation",
      "Residential",
      "Antipolo City, Rizal",
      "Completed",
      100,
      164000,
      "2026-09-28",
    ],
    [
      "Rivera Family Home",
      "Paolo Rivera",
      "Roof Repair",
      "Residential",
      "San Juan City, Metro Manila",
      "Completed",
      100,
      46500,
      "2026-09-25",
    ],
  ];
  const bookings = [],
    inspections = [],
    quotations = [],
    projects = [],
    tasks = [],
    payments = [],
    usage = [],
    feedback = [];
  specs.forEach(
    (
      [name, client, service, type, address, status, progress, total, end],
      i,
    ) => {
      const n = i + 1,
        bid = `BK-${String(n).padStart(3, "0")}`,
        iid = `IN-${String(n).padStart(3, "0")}`,
        qid = `QT-${String(n).padStart(3, "0")}`,
        pid = `PRJ-${String(n).padStart(3, "0")}`;
      const done = status === "Completed";
      bookings.push({
        id: bid,
        name: client,
        email: i === 0 ? "maria@example.com" : `client${n}@example.com`,
        phone: "0917 555 0123",
        address,
        date: "2026-09-20",
        time: "09:00",
        service,
        type,
        description: `${service} for ${name}. Please inspect existing roofing and drainage.`,
        status: "Completed",
        submitted_at: `2026-09-${String(12 + i).padStart(2, "0")}T08:01:00.000Z`,
        token: `sample-track-${n}`,
        photos: [],
      });
      inspections.push({
        id: iid,
        bookingId: bid,
        foremanId: "USR-2",
        date: "2026-09-22",
        area: 120 + i * 20,
        linear: 40,
        profile: "Rib-Type / Ribbed",
        complexity: "Moderate",
        sections: 2,
        condition: service === "Roof Installation" ? "Good" : "Damaged",
        accessories: ["Ridge Cap", "Roofing Screws", "Sealant"],
        notes: "Confirm flashing at roof transitions. Clear access available.",
        status: "Completed",
        photos: [],
      });
      const qty = service === "Roof Repair" ? 60 : 120 + i * 20,
        materialTotal = qty * 550 + 20 * 250;
      quotations.push({
        id: qid,
        bookingId: bid,
        inspectionId: iid,
        items: [
          {
            materialId: "MAT-2",
            name: "Twin Rib",
            unit: "SQM",
            quantity: qty,
            price: 550,
          },
          {
            materialId: "MAT-7",
            name: "Ridge Cap",
            unit: "LM",
            quantity: 20,
            price: 250,
          },
        ],
        charges: total - materialTotal,
        total,
        downpayment: Math.round(total * 0.3),
        status: "Approved",
        createdAt: "2026-09-23T09:00:00.000Z",
        notes: "Roofing installation, delivery and site preparation included.",
      });
      projects.push({
        id: pid,
        bookingId: bid,
        quotationId: qid,
        name,
        client,
        service,
        type,
        address,
        status,
        progress,
        start: "2026-10-01",
        end,
        foremanId: "USR-2",
        employeeIds: i < 2 ? ["USR-3", "USR-4"] : ["USR-5"],
        requirements: done,
        locked: done,
        createdAt: "2026-09-24T09:00:00.000Z",
        timeline: [
          { text: "Quotation approved", at: "2026-09-24T09:00:00.000Z" },
          {
            text: done
              ? "Project completed"
              : "Personnel assigned · project scheduled",
            at: "2026-10-01T08:00:00.000Z",
          },
        ],
      });
      [
        "Site preparation",
        "Install roofing sheets",
        "Install flashing & accessories",
        "Final inspection & site cleanup",
      ].forEach((t, j) =>
        tasks.push({
          id: `TSK-${n}-${j}`,
          projectId: pid,
          name: t,
          assigneeId: i < 2 ? "USR-3" : "USR-5",
          start: "2026-10-01",
          due: end,
          progress: done
            ? 100
            : Math.min(100, Math.max(0, progress * 4 - j * 100)),
          notes: "",
          required: true,
        }),
      );
      payments.push({
        id: `PAY-${n}`,
        projectId: pid,
        amount: done ? total : Math.round(total * (i === 2 ? 0.3 : 0.5)),
        method: i % 2 ? "Bank Transfer" : "GCash",
        date: "2026-10-01",
        reference: `ENG-2026-00${n}`,
        remarks: done ? "Full settlement" : "Initial payment",
        createdAt: "2026-10-01T10:00:00.000Z",
      });
      usage.push(
        {
          id: `USE-${n}-1`,
          projectId: pid,
          materialId: "MAT-2",
          used: Math.round((qty * progress) / 100),
          delivered: qty,
        },
        {
          id: `USE-${n}-2`,
          projectId: pid,
          materialId: "MAT-7",
          used: Math.round((20 * progress) / 100),
          delivered: 20,
        },
      );
      if (done)
        feedback.push({
          id: `FB-${n}`,
          projectId: pid,
          name: client,
          installation: 5,
          service: i === 4 ? 4 : 5,
          timeliness: 4,
          professionalism: 5,
          comments:
            i === 4
              ? "The team was professional and kept our property clean. We love our new roof!"
              : "Quick response and excellent workmanship. Thank you, ENG Roofing.",
          createdAt: "2026-09-29T12:00:00.000Z",
        });
    },
  );
  [
    [
      "Cruz Residence",
      "Elena Cruz",
      "Roof Installation",
      "Residential",
      "Pending",
      "2026-10-04T08:01:00.000Z",
    ],
    [
      "Silverline Trading",
      "Michael Tan",
      "Roof Repair",
      "Commercial",
      "Pending",
      "2026-10-04T08:07:00.000Z",
    ],
    [
      "Garcia Family Home",
      "Andrea Garcia",
      "Roof Replacement",
      "Residential",
      "For Inspection",
      "2026-10-04T08:15:00.000Z",
    ],
    [
      "Northgate Office",
      "Daniel Ong",
      "Roof Repair",
      "Commercial",
      "Approved",
      "2026-10-03T14:22:00.000Z",
    ],
  ].forEach(([title, name, service, type, status, submitted_at], i) =>
    bookings.push({
      id: `BK-00${i + 7}`,
      name,
      email: `booking${i}@example.com`,
      phone: "0918 555 0100",
      address: "Quezon City, Metro Manila",
      date: "2026-10-06",
      time: "09:00",
      service,
      type,
      description: `${title}: requesting a site visit for ${service.toLowerCase()}.`,
      status,
      submitted_at,
      token: `sample-booking-${i + 7}`,
      photos: [],
    }),
  );
  inspections.push({
    id: "IN-007",
    bookingId: "BK-009",
    foremanId: "USR-2",
    date: "2026-10-06",
    status: "Scheduled",
    area: 0,
    linear: 0,
    profile: "Not Determined",
    complexity: "Simple",
    sections: 1,
    condition: "Requires Further Assessment",
    accessories: [],
    notes: "",
    photos: [],
  });
  const attendance = [
    {
      id: "ATT-1",
      userId: "USR-3",
      projectId: "PRJ-001",
      date: "2026-10-02",
      checkIn: "2026-10-02T00:00:00.000Z",
      checkOut: "2026-10-02T08:00:00.000Z",
      hours: 8,
      latitude: 14.676,
      longitude: 121.043,
      verified: true,
      source: "Sample data",
    },
    {
      id: "ATT-2",
      userId: "USR-4",
      projectId: "PRJ-001",
      date: "2026-10-02",
      checkIn: "2026-10-02T00:00:00.000Z",
      checkOut: "2026-10-02T08:00:00.000Z",
      hours: 8,
      latitude: 14.676,
      longitude: 121.043,
      verified: true,
      source: "Sample data",
    },
  ];
  return {
    users,
    bookings,
    inspections,
    quotations,
    projects,
    tasks,
    materials,
    usage,
    attendance,
    payroll: [],
    payments,
    feedback,
    notifications: [
      {
        id: "NT-1",
        role: "Admin",
        title: "New roofing booking",
        message: "Elena Cruz requested a roof installation.",
        createdAt: "2026-10-04T08:01:00.000Z",
        read: false,
      },
      {
        id: "NT-2",
        role: "Admin",
        title: "Payment received",
        message: "Santos Residence · ₱66,250 via GCash",
        createdAt: "2026-10-03T15:30:00.000Z",
        read: false,
      },
      {
        id: "NT-3",
        role: "Admin",
        title: "Project progress updated",
        message: "St. Matthew Learning Center is now 85% complete.",
        createdAt: "2026-10-03T11:00:00.000Z",
        read: false,
      },
    ],
    emails: [],
    settings: [
      {
        id: "company",
        name: "ENG Roofing Supply & Installation Services",
        hoursPerDay: 8,
        currency: "PHP",
        payrollNote:
          "Daily rate prorated by verified hours, capped at one daily rate per day. No overtime or statutory deductions are assumed; enter approved deductions.",
      },
    ],
  };
}
